// packages/ui/components/badge.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/utils"

const badgeVariants = cva(
	"inline-flex items-center border rounded-full px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
	{
		variants: {
			variant: {
				default: "bg-primary hover:bg-primary/80 border-transparent text-primary-foreground",
				secondary: "bg-secondary hover:bg-secondary/80 border-transparent text-secondary-foreground",
				destructive: "bg-destructive hover:bg-destructive/80 border-transparent text-destructive-foreground",
				outline: "text-foreground",
			},
		},
		defaultVariants: {
			variant: "default",
		},
	},
)

export interface BadgeProps extends React.HTMLAttributes<HTMLDivElement>, VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
	return <div className={cn(badgeVariants({ variant }), className)} {...props} />
}

export { Badge, badgeVariants }

// apps/qwik-migration/src/components/ui/badge.tsx
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"
import type { QwikIntrinsicElements } from "@builder.io/qwik"
import { component$ } from "@builder.io/qwik"

const badgeVariants = cva(
	"inline-flex items-center border rounded-full px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
	{
		variants: {
			variant: {
				default: "bg-primary hover:bg-primary/80 border-transparent text-primary-foreground",
				secondary: "bg-secondary hover:bg-secondary/80 border-transparent text-secondary-foreground",
				destructive: "bg-destructive hover:bg-destructive/80 border-transparent text-destructive-foreground",
				outline: "text-foreground",
			},
		},
		defaultVariants: {
			variant: "default",
		},
	},
)

type Div = QwikIntrinsicElements["div"]

export interface BadgeProps extends Div, VariantProps<typeof badgeVariants> {}

const Badge = component$<BadgeProps>(({ class: className, variant, ...props }) => {
	return <div class={cn(badgeVariants({ variant }), className)} {...props} />
})

export { Badge, badgeVariants }
